name: clojure build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '14' # The JDK version to make available on the path.
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.10.1.739'
      - name: build java
        run: |
          cd java
          javac -d . PublicInstanceField.java
          jar cf experimentation.jar experimentation
      - run: clojure -M:test
