name: clj-kondo checks

on: [push]

jobs:
  self-lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: DeLaGuardo/clojure-lint-action@v1
      with:
        clj-kondo-args: --lint src test
        github_token: ${{ secrets.GITHUB_TOKEN }}
